apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: if2trrtb7-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/if2trrtb7-java-springboot-gitops